LOCAL_PATH := $(call my-dir)

INTRINSICS_FIXUP_SCRIPT := $(LOCAL_PATH)/fixup-intrinsics.py

.PHONY: intrinsics-fixup
.SECONDEXPANSION:
intrinsics-fixup: $$(INTERNAL_VENDORIMAGE_FILES) $$(INTERNAL_SYSTEMIMAGE_FILES)
	@python3 $(INTRINSICS_FIXUP_SCRIPT) $(TARGET_OUT_VENDOR) $(TARGET_OUT)

$(INSTALLED_VENDORIMAGE_TARGET): intrinsics-fixup
$(INSTALLED_SYSTEMIMAGE): intrinsics-fixup
